### ISSUE TITLE
ModuleNotFoundError: No module named 'xgboost'

### ISSUE THREAD

**Issue by kcbhamu** [sheriftawfikabbas/crystalfeatures#1]
When I run those script files with the provided cif file, I am getting below error:

 python3.6 descriptors_sdft.py Li10Ge\(PS6\)2_mp-696128_conventional_standard.cif 
Traceback (most recent call last):
  File "descriptors_sdft.py", line 13, in <module>
    from xgboost import XGBRegressor
ModuleNotFoundError: No module named 'xgboost'

**Comment by sheriftawfikabbas** [comment]
You just need to install xgboost before installing. To do that, just type in the command line:
`pip install xgboost`
